### ISSUE TITLE
"in" and "out" mediators are not supported inside sequence

### ISSUE THREAD

**Issue by jpvadell** [wso2/devstudio-tooling-ei#103]
**Description:**
I write "in" and "out" mediators inside a sequence, I save the file, and when I open the file again, appears empty.
At design mode, I can't find in and out mediators.
I can create it at the web console without any problem.

**Affected Product Version:**
6.1.1

**Steps to reproduce:**
create an empty sequence file. Try to add in and out mediators. with a log or send inside. Save it. Open it again.

**Comment by sohaniwso2** [comment]
Tooling does not allow to put In/Out mediators inside any arbitrary Sequence or any Proxy service. But if you create the main sequence, it will contain In/Out mediators because we definitely need In/Out mediators inside the main sequence.This is a limitation as it's impossible to represent the meaning of In/Out mediators inside a Sequence graphically.

**Comment by sohaniwso2** [comment]
Answered hence closing
