### ISSUE TITLE
Cannot save when a drop mediator is added to sequence

### ISSUE THREAD

**Issue by Drifftr** [wso2/devstudio-tooling-ei#107]
**Description:**
When two sequences are open and when we use drop mediator in either sequence an error occurs when trying to save.

**Steps to reproduce:**
1. Create two sequences
2. Add a drop mediator to first sequence.
3. Add any other mediator(Log mediator) to second sequence.
4. When trying to save the second sequence or first sequence you get the error below.
![selection_029](https://user-images.githubusercontent.com/3378323/34484276-b80f7802-efe9-11e7-8e74-d8c9e51f6082.png)

**Comment by prabushi** [comment]
This issue only happens when the opened window with the Drop mediator is located left to the current window. As a workaround we can close the opened window with the Drop mediator or move that window to right side. Then, it will be allowed to save the current window. It seems the developer studio validate all the opened windows that are located to the left side while saving the window artifacts of the current window.

**Comment by sohaniwso2** [comment]
moved at https://github.com/wso2/product-ei/issues/2476
