### ISSUE TITLE
Improve usability of the DSS Editor

### ISSUE THREAD

**Issue by sohaniwso2** [wso2/devstudio-tooling-ei#311]
**Description:**
Needs to be compatible with the Management Console
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
Originally reported in https://github.com/wso2/product-ei/issues/4426

You need to know detailed information about the schema and exact output message/format you want to generate in order to create a data service. If there's a default mode where, a user cloud introspect the DB/table, select columns or specify the custom query (should be the last resort) and then automatically create an output mapping this will enhance developer experience quite a bit.

Creating an output mapping and ability to change your own message should be the last option for advanced users.

jira: https://wso2.org/jira/browse/DEVTOOLEI-1139
