### ISSUE TITLE
[DS4.1.0]Property tab becomes blank when I click on other tabs

### ISSUE THREAD

**Issue by ushanib** [wso2/devstudio-tooling-ei#33]
Create a payload factory mediator with properties (E.g., format and arguments)
![screenshot from 2017-07-07 14-48-29](https://user-images.githubusercontent.com/12966170/27951681-5dc89318-6323-11e7-8e1e-b86070ad63f1.png)

Now click on Servers or Markers tab and click back on property tab. It is blank. When you click back on Source or design it will appear. This is not a major issue since there is a work around to appear it.

![screenshot from 2017-07-07 14-49-07](https://user-images.githubusercontent.com/12966170/27951718-7a65bfa0-6323-11e7-9b56-cb5d23af9e59.png)

**Comment by ushanib** [comment]
This issue can be seen in other mediators as well

**Comment by prabushi** [comment]
According to the default behavior of Integration Studio, the properties view will be loaded depending on what is selected from the design view. Therefore, when you click on another tab, focus will be set to a different location rather the previously selected mediator. Hence, properties view be reloaded with the properties view of the currently selected location. (In this case, there are no properties allocated to the selected location)
This is the expected behavior of the EMF and EEF frameworks.
