### ISSUE TITLE
Add guide to run DSS Sample in Tooling with embedded MI

### ISSUE THREAD

**Issue by Nirothipan** [wso2/devstudio-tooling-ei#468]
**Description:**
$subject.

We have the subject for ESB samples ( for both MI and EI )
DSS - Student DataService Sample has only guide to run in EI but not in embedded MI. We need to add a guide for that as well.

**Comment by prabushi** [comment]
Since we do not encourage the end-user to make changes for the embedded MI (in this case, we have to manually add the driver jar into MI), as it is hard to revert the changes, and it is pretty much the same steps that we need to follow, compared to EI, we will not be adding a guide to run DSS samples on the embedded MI.
