### ISSUE TITLE
No option to enable statistics and tracing for an API via Dev Studio

### ISSUE THREAD

**Issue by sashikamw** [wso2/devstudio-tooling-ei#53]
**Environment**
OS - ubuntu 15.10
Java - JDK jdk1.8.0_66
Dev studio with updates (EI611)
Remote Server - Running in windows server 2012 R2

**Observations**
Could not find an option to enable statistics and tracing for an API via Dev Studio

![api](https://user-images.githubusercontent.com/14962228/28198907-1b9943e6-687f-11e7-8293-21b6f4000c54.png)

**Comment by sohaniwso2** [comment]
@sashikamw : When we create an API using the wizard, it opens the API in ESB graphical editor with a resource ( so the design view contains the resources of the API ), hence the property view is associated with the resource and not with the API. 

Since the API cannot be represented in the design view, the mentioned properties (statistics and tracing) cannot be edited via design view but still you can edit the source view and add those two properties and those will get serialized.

**Comment by sashikamw** [comment]
Statistics can be configured using the source view as mentioned above through developer stuido
