### ISSUE TITLE
Could not find an option to define endpoint names within Load balancing EP

### ISSUE THREAD

**Issue by sashikamw** [wso2/devstudio-tooling-ei#55]
**Environment**
OS - ubuntu 15.10
Java - JDK jdk1.8.0_66
Dev studio with updates (EI611)

**Steps to recreate the issue**
1. Create a LoadBalancing EP via EI tooling

**Observations**
1. Could not find an option to provide a name for the address endpoint when defining a load balancing endpoint

![loadbalancingepdevstudio](https://user-images.githubusercontent.com/14962228/28257438-83a9c6de-6ae8-11e7-94f3-eae7747ddea9.png)

Impact - After creating a LB Endpoint via EI tooling following configuration got saved. Since the name is a mandatory filed in the EI management console, it should be available in the Dev Studio

```
<?xml version="1.0" encoding="UTF-8"?>
<endpoint name="LoadBalanceEP" xmlns="http://ws.apache.org/ns/synapse">
    <loadbalance algorithm="org.apache.synapse.endpoints.algorithms.RoundRobin">
        <endpoint name="endpoint_urn_uuid_6179155B57847314A657084710149040-304004407">
            <address statistics="enable" trace="enable" uri="http://10.100.11.26:9000/services/SimpleStockQuoteService"/>
        </endpoint>
        <endpoint>
            <address statistics="enable" trace="enable" uri="http://10.100.11.26:9001/services/SimpleStockQuoteService"/>
        </endpoint>
    </loadbalance>
</endpoint>
```

**Comment by sohaniwso2** [comment]
@sashikamw : According to [1], endpoint name is not a mandatory field for complex endpoints. So not having a name seems not an issue when considering the functionality. ( May be in EI management console this field has become a mandatory field due to a UI validation).

Also, I think you are requesting a name for the endpoint because you might need to view stats for that particular endpoint, if that's the case you can edit the source view (of the tool) and add a name, and it will get serialized in the tool

[1] https://docs.wso2.com/display/EI611/Sample+154%3A+Load+Balancing+with+Proxy+Services

**Comment by sohaniwso2** [comment]
closing the issue since this is verified and can use the mentioned workaround if someone wants to add a name
