### ISSUE TITLE
[Integrator]& should be allowed in endpoint in synapse level. User should explicitly escape it

### ISSUE THREAD

**Issue by ushanib** [wso2/devstudio-tooling-ei#66]
http://demo2424780.mockable.io/test?ush=1&a=2 should be given as below when defining an endpoint http://demo2424780.mockable.io/test?ush=1&amp;a=2

**Comment by sohaniwso2** [comment]
@ushanib : '&amp;'  is the HTML entity reference for '&'. 

When you define the URL via properties view ( in design view) or when you use the endpoint form editor you can simply use the URL as 'http://demo2424780.mockable.io/test?ush=1&a=2' and it will serialize the URL as 'http://demo2424780.mockable.io/test?ush=1&amp;a=2' in the source view. 

Note: If you are using the source view to add the URL (or using endpoint creation wizard to create a new endpoint), you need to use ''&amp;' instead of '&' to avoid XML passing errors. (the reason for the error is xml validation hence this is not a bug)

Please refer [1] on including an ampersand (&) character in an XML document

[1] https://stackoverflow.com/questions/14500800/how-can-i-include-an-ampersand-character-in-an-xml-document

**Comment by ushanib** [comment]
Closing the issue based on the above comment.
