### ISSUE TITLE
Improve Connector related user experience

### ISSUE THREAD

**Issue by Drifftr** [wso2/devstudio-tooling-ei#885]
**Description:**
Currently the adding a connector and using it is not intuitive from tooling aspect. Need to improve it.
Suggestions - 

1. Revamp Connector properties view
2. Add "Add/Remove connector" button to palette

**Comment by prabushi** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/1150, https://github.com/wso2/devstudio-tooling-esb/pull/1151, https://github.com/wso2/devstudio-tooling-esb/pull/1157, https://github.com/wso2/devstudio-tooling-esb/pull/1158, https://github.com/wso2/devstudio-tooling-esb/pull/1161, and https://github.com/wso2/devstudio-tooling-esb/pull/1162
