### ISSUE TITLE
GUI issue with Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/devstudio-tooling-ei#958]
**Description:**
The GUI of Integration studio has not scaled well as the font and icons are too small.

![image](https://user-images.githubusercontent.com/25485783/80973710-5ea14d00-8e3d-11ea-9851-2e8ae456c75d.png)

**OS, DB, other environment details and versions:** 
Ubuntu 20.04 LTS
Resolution - 2560x1440

**Comment by prabushi** [comment]
This issue was observed on Linux 20 as the display scaling with high resolution was not picked up by the internal browser in Eclipse. However, we have done some modifications to make the fonts more clearer with the new getting started page revamp. 
If you change your display settings as a workaround for the time being, you can observe correct scaling of fonts. (eg: Resolution 2048x1152 scale 100%)
