### ISSUE TITLE
After creating a new data mapper config, Int. Studio shows a blank screen (need to scroll up for input/output section)

### ISSUE THREAD

**Issue by wx-yz** [wso2/devstudio-tooling-ei#995]
**Description:**
Just after creating a new data mapper config Integration Studio shows a blank screen. Need to scroll up for input/output section

<img width="1440" alt="Screen Shot 2020-05-26 at 10 44 40 AM" src="https://user-images.githubusercontent.com/57770159/82933138-55883500-9f3e-11ea-9a97-e17ab4668134.png">

**Affected Product Version:**
Integration Studio latest

<img width="690" alt="Screen Shot 2020-05-26 at 10 49 06 AM" src="https://user-images.githubusercontent.com/57770159/82933349-9d0ec100-9f3e-11ea-8493-64ed38c6963d.png">

**OS, DB, other environment details and versions:**    
macOS Catalina 10.15.4

**Comment by vanjikumaran** [comment]
The screen is empty since your focus area is shifted, please refocus using Outline.

<img width="1412" alt="Screen Shot 2020-05-26 at 11 28 52 AM" src="https://user-images.githubusercontent.com/3397321/82936961-3391b100-9f44-11ea-929a-70f2e6d5b981.png">

**Comment by wx-yz** [comment]
Yes, I can also scroll up and see the input output section. However, this only happens on Windows. For a new user, and for someone who's new to Integration Studio, refocusing should happen automatically.

**Comment by rosensilva** [comment]
Fixed with https://github.com/wso2/devstudio-tooling-esb/pull/1119. Please try updating the tool(Help->Check for updates and select all updates). This should be fixed in  7.0.0.202005250425 update.

**Comment by wx-yz** [comment]
@rosensilva Ran the update check and it doesn't show me any updates

**Comment by rosensilva** [comment]
@wx-yz I have tested on a windows machine and updates are working fine. Seems like there's an issue with your updater tool(due to a network issue, corrupted Integration Studio app). Anyway, we can directly update the integration studio using the "install new software" option.
To update directly, follow these steps,
1. Open "Install New Software..." from Help->Install New Software...
2. Click the "Add.." button 
⋅⋅1. Add Kernel as an entry
Location: http://product-dist.wso2.com/p2/developer-studio-kernel/4.3.0/kernel/updates/
..2. Add Platform as an entry
Location: http://product-dist.wso2.com/p2/developer-studio-kernel/4.3.0/platform-bundles/updates/7.0.0/
..3 Add ESB as an entry 
Location: http://product-dist.wso2.com/p2/developer-studio-kernel/4.3.0/esb-tools/updates/7.0.0/
3. Select all and update
